// <auto-generated />
using System;
using JobNexus.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobNexus.Data.Migrations
{
    [DbContext(typeof(JobNexusContext))]
    partial class JobNexusContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Applied", b =>
                {
                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.Property<int>("JobId")
                        .HasColumnType("int")
                        .HasColumnName("job_id");

                    b.HasKey("Username", "JobId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "JobId" }, "job_id");

                    b.ToTable("Applied", (string)null);
                });

            modelBuilder.Entity("JobNexus.Core.Models.Certification", b =>
                {
                    b.Property<int>("CertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cert_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CertId"));

                    b.Property<string>("CertName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cert_name");

                    b.Property<DateTime?>("DateGiven")
                        .HasColumnType("datetime")
                        .HasColumnName("date_given");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.HasKey("CertId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Username" }, "username");

                    b.ToTable("Certification", (string)null);
                });

            modelBuilder.Entity("JobNexus.Core.Models.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("company_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CompanyId"));

                    b.Property<string>("CompanyName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("company_name");

                    b.Property<string>("Industry")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("Website_url");

                    b.HasKey("CompanyId")
                        .HasName("PRIMARY");

                    b.ToTable("Company", (string)null);
                });

            modelBuilder.Entity("JobNexus.Core.Models.Job", b =>
                {
                    b.Property<int>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Job_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("JobId"));

                    b.Property<string>("ApplyUrl")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("apply_url");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("company_id");

                    b.Property<DateTime?>("DatePosted")
                        .HasColumnType("datetime")
                        .HasColumnName("date_posted");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("description");

                    b.Property<int?>("Pay")
                        .HasColumnType("int")
                        .HasColumnName("pay");

                    b.Property<int?>("SourceId")
                        .HasColumnType("int")
                        .HasColumnName("source_id");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("title");

                    b.HasKey("JobId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CompanyId" }, "company_id");

                    b.HasIndex(new[] { "SourceId" }, "source_id");

                    b.ToTable("Job", (string)null);
                });

            modelBuilder.Entity("JobNexus.Core.Models.JobSource", b =>
                {
                    b.Property<int>("SourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("source_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SourceId"));

                    b.Property<string>("SourceName")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("source_name");

                    b.HasKey("SourceId")
                        .HasName("PRIMARY");

                    b.ToTable("JobSource", (string)null);
                });

            modelBuilder.Entity("JobNexus.Core.Models.Profile", b =>
                {
                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.Property<string>("Bio")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("bio");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("password");

                    b.HasKey("Username")
                        .HasName("PRIMARY");

                    b.ToTable("Profile", (string)null);
                });

            modelBuilder.Entity("JobNexus.Core.Models.Resume", b =>
                {
                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.Property<string>("Education")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("education");

                    b.Property<string>("JobExp")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("Job_Exp");

                    b.Property<string>("Projects")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("projects");

                    b.Property<string>("Recommendations")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("recommendations");

                    b.HasKey("Username")
                        .HasName("PRIMARY");

                    b.ToTable("Resume", (string)null);
                });

            modelBuilder.Entity("JobNexus.Core.Models.Skill", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("skill_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SkillId"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("category");

                    b.Property<string>("SkillName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("skill_name");

                    b.HasKey("SkillId")
                        .HasName("PRIMARY");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("Obtained", b =>
                {
                    b.Property<int>("SkillId")
                        .HasColumnType("int")
                        .HasColumnName("skill_id");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.HasKey("SkillId", "Username")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Username" }, "username")
                        .HasDatabaseName("username1");

                    b.ToTable("Obtained", (string)null);
                });

            modelBuilder.Entity("Require", b =>
                {
                    b.Property<int>("SkillId")
                        .HasColumnType("int")
                        .HasColumnName("skill_id");

                    b.Property<int>("JobId")
                        .HasColumnType("int")
                        .HasColumnName("job_id");

                    b.HasKey("SkillId", "JobId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "JobId" }, "job_id")
                        .HasDatabaseName("job_id1");

                    b.ToTable("Requires", (string)null);
                });

            modelBuilder.Entity("Applied", b =>
                {
                    b.HasOne("JobNexus.Core.Models.Job", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .IsRequired()
                        .HasConstraintName("Applied_ibfk_2");

                    b.HasOne("JobNexus.Core.Models.Profile", null)
                        .WithMany()
                        .HasForeignKey("Username")
                        .IsRequired()
                        .HasConstraintName("Applied_ibfk_1");
                });

            modelBuilder.Entity("JobNexus.Core.Models.Certification", b =>
                {
                    b.HasOne("JobNexus.Core.Models.Profile", "UsernameNavigation")
                        .WithMany("Certifications")
                        .HasForeignKey("Username")
                        .HasConstraintName("Certification_ibfk_1");

                    b.Navigation("UsernameNavigation");
                });

            modelBuilder.Entity("JobNexus.Core.Models.Job", b =>
                {
                    b.HasOne("JobNexus.Core.Models.Company", "Company")
                        .WithMany("Jobs")
                        .HasForeignKey("CompanyId")
                        .HasConstraintName("Job_ibfk_2");

                    b.HasOne("JobNexus.Core.Models.JobSource", "Source")
                        .WithMany("Jobs")
                        .HasForeignKey("SourceId")
                        .HasConstraintName("Job_ibfk_1");

                    b.Navigation("Company");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("JobNexus.Core.Models.Resume", b =>
                {
                    b.HasOne("JobNexus.Core.Models.Profile", "UsernameNavigation")
                        .WithOne("Resume")
                        .HasForeignKey("JobNexus.Core.Models.Resume", "Username")
                        .IsRequired()
                        .HasConstraintName("Resume_ibfk_1");

                    b.Navigation("UsernameNavigation");
                });

            modelBuilder.Entity("Obtained", b =>
                {
                    b.HasOne("JobNexus.Core.Models.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .IsRequired()
                        .HasConstraintName("Obtained_ibfk_1");

                    b.HasOne("JobNexus.Core.Models.Profile", null)
                        .WithMany()
                        .HasForeignKey("Username")
                        .IsRequired()
                        .HasConstraintName("Obtained_ibfk_2");
                });

            modelBuilder.Entity("Require", b =>
                {
                    b.HasOne("JobNexus.Core.Models.Job", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .IsRequired()
                        .HasConstraintName("Requires_ibfk_2");

                    b.HasOne("JobNexus.Core.Models.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .IsRequired()
                        .HasConstraintName("Requires_ibfk_1");
                });

            modelBuilder.Entity("JobNexus.Core.Models.Company", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("JobNexus.Core.Models.JobSource", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("JobNexus.Core.Models.Profile", b =>
                {
                    b.Navigation("Certifications");

                    b.Navigation("Resume");
                });
#pragma warning restore 612, 618
        }
    }
}
